package id.ritmagula.backend.api;

public enum ApplicationCode {
    SYSTEM_READY,
    COLLECTING_DATA,
    READY_TO_SCREEN,
    RESULT_AVAILABLE,
    ABSTAINED,
    CONFIRMATION_REQUIRED,
    PARTIAL_CONFIRMATION_REQUIRED,
    MANUAL_ENTRY_REQUIRED,
    MODEL_UNAVAILABLE,
    SESSION_RESET,
    UNAUTHORIZED,
    NOT_FOUND,
    UPLOAD_TOO_LARGE,
    VALIDATION_ERROR,
    SERVICE_TIMEOUT,
    NETWORK_ERROR,
    INTERNAL_ERROR
}
